@url = http://localhost:3000

### Login para obtener token
# @name login
POST {{url}}/auth/login
Content-Type: application/json

{
  "email": "juanpabloocampo61@gmail.com",
  "contraseña": "Prog4tp3"
}

### Token para usar en pruebas
@token = {{login.response.body.token}}

### Obtener todos los usuarios
GET {{url}}/usuarios
Authorization: Bearer {{token}}

### Obtener usuario por ID
GET {{url}}/usuarios/1
Authorization: Bearer {{token}}

### Crear usuario
POST {{url}}/usuarios
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "nombre": "Sandro",
  "email": "sandromansilla2@gmail.com",
  "contraseña": "sandro12345"
}

### Modificar usuario
PUT {{url}}/usuarios/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "nombre": "Celeste",
  "email": "celesterodriguez21@gmail.com"
}

### Eliminar usuario
DELETE {{url}}/usuarios/1
Authorization: Bearer {{token}}